In [1]:
import pandas as pd
import numpy as np

In [6]:
s = pd.Series([10, 20, 30, 40, 50])
s[2]

np.int64(30)

In [47]:
df = {
    'Name': ['철수', '영희', '민수', '지민'],
    'Age': [25, 28, 22, 30],
    'Score': [85, 90, 78, 95]
}
# df = pd.DataFrame(df)

df = pd.DataFrame(df, index=['A', 'B', 'C', 'D'])
df.loc['B':'D']

# - index: 'A', 'C'
# - columns: 'Name', 'Age'
df.loc[['A', 'C'], ['Name', 'Age']]

  Name  Age
A   철수   25
C   민수   22

In [93]:
products = pd.read_csv('data/olist_products_dataset.csv')
products.head(5)
products.tail(5)
products.shape
products.columns
products.index
# products.info()
products.describe()
products[['product_id', 'product_category_name', 'product_weight_g']]
products[(products['product_name_lenght'] <= 10) & (products.product_photos_qty >= 2)]

target_categories = ['perfumaria', 'bebes']
products[products.product_category_name.isin(target_categories)]

products[products.product_category_name.str.contains('deco')]

df = products.rename(columns={
    'product_name_lenght': 'name_len',
    'product_description_lenght': 'desc_len'
})

products['weight_kg'] = products['product_weight_g'] / 1000

products = products.drop('product_description_lenght', axis=1)
products.drop([0, 1, 2], axis=0)

products.isna().sum()
products.dropna()

products['product_category_name'] = products.product_category_name.fillna('Unknown')

In [97]:
products[products.product_category_name.isna()]
products[products.product_category_name == 'Unknown']
products.isna().sum()

product_id                 0
product_category_name      0
product_name_lenght      610
product_photos_qty       610
product_weight_g           2
product_length_cm          2
product_height_cm          2
product_width_cm           2
weight_kg                  2
dtype: int64

In [102]:
products.sort_values('product_weight_g', ascending=False)
products.sort_index(ascending=False)

,product_id,product_category_name,product_name_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,weight_kg
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,1.0,2083.0,12.0,2.0,7.0,2.083
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,2.0,700.0,31.0,13.0,20.0,0.700
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,1.0,1400.0,27.0,7.0,27.0,1.400
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,1.0,1700.0,16.0,19.0,16.0,1.700
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,2.0,12300.0,40.0,40.0,40.0,12.300
...,...,...,...,...,...,...,...,...,...
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,4.0,625.0,20.0,17.0,13.0,0.625
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,1.0,371.0,26.0,4.0,26.0,0.371
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,1.0,154.0,18.0,9.0,15.0,0.154
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,1.0,1000.0,30.0,18.0,20.0,1.000
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,1.0,225.0,16.0,10.0,14.0,0.225

In [103]:
products.product_name_lenght.count()

np.int64(32341)

In [106]:
products.product_name_lenght.isna().sum()

np.int64(610)

In [109]:
products.product_name_lenght.shape[0] - 610

32341

In [115]:
len(products.product_category_name.unique())

74

In [116]:
products.product_category_name.nunique()

74

In [119]:
products.product_category_name.value_counts().head(10)

product_category_name
cama_mesa_banho           3029
esporte_lazer             2867
moveis_decoracao          2657
beleza_saude              2444
utilidades_domesticas     2335
automotivo                1900
informatica_acessorios    1639
brinquedos                1411
relogios_presentes        1329
telefonia                 1134
Name: count, dtype: int64

# 한화짱 

우리는 정말 훌륭한 회사에서 일하고 있다

- **볼드체**
- ~~스트라이크~~

$$ x^2 + \frac{5}{x}  $$

In [124]:
def classify(w):
    if pd.isna(w): return 'Unknown'
    if w >= 1000: return 'Heavy'
    else: return 'Light'        
products.product_weight_g.apply(classify)

0        Light
1        Heavy
2        Light
3        Light
4        Light
         ...
32946    Heavy
32947    Heavy
32948    Heavy
32949    Light
32950    Heavy
Name: product_weight_g, Length: 32951, dtype: str

In [125]:
products

,product_id,product_category_name,product_name_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,weight_kg
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,1.0,225.0,16.0,10.0,14.0,0.225
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,1.0,1000.0,30.0,18.0,20.0,1.000
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,1.0,154.0,18.0,9.0,15.0,0.154
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,1.0,371.0,26.0,4.0,26.0,0.371
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,4.0,625.0,20.0,17.0,13.0,0.625
...,...,...,...,...,...,...,...,...,...
32946,a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,2.0,12300.0,40.0,40.0,40.0,12.300
32947,bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,1.0,1700.0,16.0,19.0,16.0,1.700
32948,9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,1.0,1400.0,27.0,7.0,27.0,1.400
32949,83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,2.0,700.0,31.0,13.0,20.0,0.700
32950,106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,1.0,2083.0,12.0,2.0,7.0,2.083

In [126]:
products.set_index('product_id')

,product_category_name,product_name_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,weight_kg
product_id,,,,,,,,
1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,1.0,225.0,16.0,10.0,14.0,0.225
3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,1.0,1000.0,30.0,18.0,20.0,1.000
96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,1.0,154.0,18.0,9.0,15.0,0.154
cef67bcfe19066a932b7673e239eb23d,bebes,27.0,1.0,371.0,26.0,4.0,26.0,0.371
9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,4.0,625.0,20.0,17.0,13.0,0.625
...,...,...,...,...,...,...,...,...
a0b7d5a992ccda646f2d34e418fff5a0,moveis_decoracao,45.0,2.0,12300.0,40.0,40.0,40.0,12.300
bf4538d88321d0fd4412a93c974510e6,construcao_ferramentas_iluminacao,41.0,1.0,1700.0,16.0,19.0,16.0,1.700
9a7c6041fa9592d9d9ef6cfe62a71f8c,cama_mesa_banho,50.0,1.0,1400.0,27.0,7.0,27.0,1.400
83808703fc0706a22e264b9d75f04a2e,informatica_acessorios,60.0,2.0,700.0,31.0,13.0,20.0,0.700
106392145fca363410d287a815be6de4,cama_mesa_banho,58.0,1.0,2083.0,12.0,2.0,7.0,2.083