In [1]:
import pandas as pd
import numpy as np

# Loading Data

In [2]:
customers = pd.read_csv('./data/olist_customers_dataset.csv')
orders = pd.read_csv('./data/olist_orders_dataset.csv')
items = pd.read_csv('./data/olist_order_items_dataset.csv')
payments = pd.read_csv('./data/olist_order_payments_dataset.csv')
reviews = pd.read_csv('./data/olist_order_reviews_dataset.csv')
products = pd.read_csv('./data/olist_products_dataset.csv')
sellers = pd.read_csv('./data/olist_sellers_dataset.csv')
transaction = pd.read_csv('./data/product_category_name_translation.csv')

In [13]:
orders.shape

(99441, 8)

In [15]:
joined = pd.merge(orders, customers, on='customer_id', how='right')
print(joined.shape)
joined.head(3)

(99441, 12)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,sao paulo,SP
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,barreiras,BA
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,vianopolis,GO

In [21]:
orders.head(3)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00

In [30]:
payments
df = pd.merge(orders, payments, on='order_id', how='inner')
df[["order_id", "order_status", "payment_type", "payment_value"]]

,order_id,order_status,payment_type,payment_value
0,e481f51cbdc54678b7cc49136f2d6af7,delivered,credit_card,18.12
1,e481f51cbdc54678b7cc49136f2d6af7,delivered,voucher,2.00
2,e481f51cbdc54678b7cc49136f2d6af7,delivered,voucher,18.59
3,53cdb2fc8bc7dce0b6741e2150273451,delivered,boleto,141.46
4,47770eb9100c2d0c44946d9cf07ec65d,delivered,credit_card,179.12
...,...,...,...,...
103881,9c5dedf39a927c1b2549525ed64a053c,delivered,credit_card,85.08
103882,63943bddc261676b46f01ca7ac2f7bd8,delivered,credit_card,195.00
103883,83c1379a015df1e13d02aae0204711ab,delivered,credit_card,271.01
103884,11c177c8e97725db2631073c19f07b62,delivered,credit_card,441.16
103885,66dea50a8b16d9b4dee7af250b4be1a5,delivered,debit_card,86.86

In [41]:
df = pd.merge(orders, items, on='order_id', how='inner', suffixes=('_order', '_item'))
df.head(3).columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'order_item_id', 'product_id', 'seller_id', 'shipping_limit_date',
       'price', 'freight_value'],
      dtype='str')

In [44]:
top3 = items.head(3)
bottom3 = items.tail(3)

pd.concat([top3, bottom3])

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
112647,fffce4705a9662cd70adb13d4a31832d,1,72a30483855e2eafc67aee5dc2560482,c3cfdc648177fdbbbb35635a37472c53,2017-10-30 17:14:25,99.90,16.95
112648,fffe18544ffabc95dfada21779c9644f,1,9c422a519119dcad7575db5af1ba540e,2b3e4a2a3ea8e01938cabda2a3e5cc79,2017-08-21 00:04:32,55.99,8.72
112649,fffe41c64501cc87c801fd61db3f6244,1,350688d9dc1e75ff97be326363655e01,f7ccf836d21b2fb1de37564105216cc1,2018-06-12 17:10:13,43.00,12.79

In [35]:
items.head(2)dd

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.9,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.9,19.93

In [50]:
step1 = pd.merge(orders, customers, on='customer_id', how='inner')
step2 = pd.merge(step1, items, on='order_id', how='inner')
step3 = pd.merge(step2, products, on='product_id', how='inner')
step4 = pd.merge(step3, sellers, on='seller_id', how='inner')
master = pd.merge(step4, transaction, on='product_category_name', how='inner')

In [54]:
master['total_paid'] = master['price'] + master['freight_value']

In [57]:
master.groupby(['customer_state', 'customer_city'])['total_paid'].mean()

customer_state  customer_city
AC              brasileia                   46.510000
                cruzeiro do sul            375.686667
                epitaciolandia             139.520000
                manoel urbano              248.710000
                porto acre                 104.350000
                                              ...
TO              silvanopolis               273.880000
                sitio novo do tocantins    119.067500
                taguatinga                 151.483333
                tocantinopolis             118.410000
                xambioa                    143.253333
Name: total_paid, Length: 4283, dtype: float64

In [60]:
master
# - product_category_name_english <- group by 한 이후에 
# - product_photos_qty 총합

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,customer_unique_id,customer_zip_code_prefix,...,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,seller_city,seller_state,product_category_name_english,total_paid
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00,7c396fd4830fd04220f754e42b4e5bff,3149,...,4.0,500.0,19.0,8.0,13.0,9350,maua,SP,housewares,38.71
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00,af07308b275d755c9edb36a90c618231,47813,...,1.0,400.0,19.0,13.0,19.0,31570,belo horizonte,SP,perfumery,141.46
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00,3a653a41f6f9fc3d2a113cf8398680e8,75265,...,1.0,420.0,24.0,19.0,21.0,14840,guariba,SP,auto,179.12
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00,7c142cf63193a1473d2e66489a9ae977,59296,...,3.0,450.0,30.0,10.0,20.0,31842,belo horizonte,MG,pet_shop,72.20
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00,72632f0f9dd73dfee390c9b22eb56dd6,9195,...,4.0,250.0,51.0,15.0,15.0,8752,mogi das cruzes,SP,stationery,28.62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111018,63943bddc261676b46f01ca7ac2f7bd8,1fca14ff2861355f6e5f14306ff977a7,delivered,2018-02-06 12:58:58,2018-02-06 13:10:37,2018-02-07 23:22:42,2018-02-28 17:37:56,2018-03-02 00:00:00,da62f9e57a76d978d02ab5362c509660,11722,...,4.0,4950.0,40.0,10.0,40.0,17602,tupa,SP,baby,195.00
111019,83c1379a015df1e13d02aae0204711ab,1aa71eb042121263aafbe80c1b562c9c,delivered,2017-08-27 14:46:43,2017-08-27 15:04:16,2017-08-28 20:52:26,2017-09-21 11:24:17,2017-09-27 00:00:00,737520a9aad80b3fbbdad19b66b37b30,45920,...,2.0,13300.0,32.0,90.0,22.0,8290,sao paulo,SP,home_appliances_2,271.01
111020,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,1.0,6550.0,20.0,20.0,20.0,37175,ilicinea,MG,computers_accessories,220.58
111021,11c177c8e97725db2631073c19f07b62,b331b74b18dc79bcdf6532d51e1637c1,delivered,2018-01-08 21:28:27,2018-01-08 21:36:21,2018-01-12 15:35:03,2018-01-25 23:32:54,2018-02-15 00:00:00,5097a5312c8b157bb7be58ae360ef43c,28685,...,1.0,6550.0,20.0,20.0,20.0,37175,ilicinea,MG,computers_accessories,220.58
111022,66dea50a8b16d9b4dee7af250b4be1a5,edb027a75a1449115f6b43211ae02a24,delivered,2018-03-08 20:57:30,2018-03-09 11:20:28,2018-03-09 22:11:59,2018-03-16 13:08:30,2018-04-03 00:00:00,60350aa974b26ff12caad89e55993bd6,83750,...,1.0,150.0,16.0,7.0,15.0,14407,franca,SP,health_beauty,86.86

# Visualization

In [63]:
import matplotlib.pyplot as plt
import seaborn as sns

In [62]:
customers = pd.read_csv('./data/olist_customers_dataset.csv')
orders = pd.read_csv('./data/olist_orders_dataset.csv')
items = pd.read_csv('./data/olist_order_items_dataset.csv')
payments = pd.read_csv('./data/olist_order_payments_dataset.csv')
reviews = pd.read_csv('./data/olist_order_reviews_dataset.csv')
products = pd.read_csv('./data/olist_products_dataset.csv')
sellers = pd.read_csv('./data/olist_sellers_dataset.csv')
transaction = pd.read_csv('./data/product_category_name_translation.csv')

In [64]:
step1 = pd.merge(orders, customers, on='customer_id', how='inner')
step2 = pd.merge(step1, items, on='order_id', how='inner')
step3 = pd.merge(step2, products, on='product_id', how='inner')
step4 = pd.merge(step3, sellers, on='seller_id', how='inner')
master = pd.merge(step4, transaction, on='product_category_name', how='inner')

In [67]:
master['total_paid'] = master['price'] + master['freight_value']
master['order_purchase_timestamp'] = pd.to_datetime(master['order_purchase_timestamp'])

In [65]:
master.groupby('year_month')['total_paid'].sum()

KeyError: 'year_month'